# Generated by Django 5.1.1 on 2024-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquadMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('pet_name', models.CharField(max_length=100)),
                ('traits', models.TextField()),
                ('movie_dialogue', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('video', models.URLField(blank=True)),
            ],
        ),
    ]
